### ISSUE TITLE
[Feature Request]: Custom Tab Completion + Optional Named Parameters

### ISSUE THREAD

**Issue by bundabrg** [aikar/commands#177] opened 2018-10-23 02:04 UTC
I have some commands that have optional parameters that may or may not be there. The general method I use is to prefix the optional parameter with its name and a colon.

For example:
```
/gc economy buy LOG qty:1 cost:123 type:vault player:PlayerName
```
The above command has several named optional parameters (qty, cost, type, player). Their order doesn't matter. Optionals have to occur after non-optionals

It would be nice if:
1. ACF can provide the name parameters feature. Perhaps an annotation with the list of names available and a parameter that contains a hashmap of name:value pairs OR maybe the parameters can be provided and will be null if not used OR the existing Optional annotation can be reworked in a backwards compatible way. I can work around this obviously by just having an end parameter consume everything and split it out myself.

2. Having the ability for TabCompletion to work with these named parameters. It can provide a list of unused 'name:' for any fields at the end of non-named parameters. In the example above when the player has not yet entered 'type:vault', it would show a list ['type:', 'player:'] (since 'qty' and 'cost' are already used) as the available named parameters left. When the colon is found it then can have custom tab completion on that (IE, after entering 'type:' it then shows a list of types). I have not yet worked out how to use the existing framework for this (Would need either a way to customize how tab completions work).

Possible example code:
```
@CommandAlias("gc")
@SubCommand("economy")
public class GCEconomy extends Base Command {
    
    @SubCommand("buy")
    @Description("Buy an item")
    @CommandCompletion("@item qty:@range:64 type:@etypes player:@players")
    public void onBuy(CommandSender sender, String item, @Named Integer qty, @Named Double cost, @Named EconomyType etype, @Named OfflinePlayer player, @Optional String args) { ... }
```
All the ```@Named``` parameters are the named optional parameters.  It could potentially have an optional parameter to specify the name of the option (IE: ```@Named("q") Integer qty```  would have 'q:' as the name parameter). The ending ```@Optional``` parameter gets all the unconsumed input as normal. So if the following was provided:
```
item something type:stone unknown:diamond
```
then the final 'args' argument would contain 'something unknown:diamond'.

It has a reworked @CommandCompletion that allows one to namespace an option with the name. If missing it assumes no special tab completion for that option

**Comment by aikar** [comment] 2018-10-23 03:33
Duplicate of https://github.com/aikar/commands/issues/150

I'll add a note over there to consider tab completion support and to see this for an idea.

**Closed by aikar** 2018-10-23 03:33 UTC
