### ISSUE TITLE
Document Exception handling

### ISSUE THREAD

**Issue by SupaHam** [aikar/commands#56] opened 2017-07-06 03:20 UTC
Wiki lacks documentation for exception handling overall. Please document it, and specifically the fact that the method receives InvocationTargetException as opposed to the exception that caused it. I personally would consider passing the cause, but if this is an umbrella exception catching feature, maybe keep it as is. :)

Thanks

**Comment by aikar** [comment] 2017-07-09 03:20
Duplicate of #7 :P

**Closed by aikar** 2017-07-09 03:20 UTC

**Comment by aikar** [comment] 2017-12-14 03:32
@SupaHam per 52c95c3 I've deployed an update to unwrap InvocationTargetException.

I misread this as purely about the docs, but ITE would be a bug as yeah we want the real exception.
