### ISSUE TITLE
Language file not being found w/ multiple plugin setup

### ISSUE THREAD

**Issue by TehNeon** [aikar/commands#98] opened 2018-02-04 10:50 UTC
So in my setup of ACF, I have 1 plugin which is a Library/Utilities plugin. This plugin has ACF built into it, which all the other plugins rely on it having. So with that being said, in one of my plugins I want to use locale but have run into an issue. It will not pick up the locale file unless it's apart of the Library plugin. 

So here is a bit of a run down of when it isn't working:
```
PluginA:
- Library plugin that has ACF built in
- acf-pluginb.properties is NOT in the resources

PluginB:
- Depends on PluginA
- acf-pluginb.properties is inside the resources
- MessageKeys are not being picked up properly (MessageKey are being executed from PluginB)
```

So here is what it looks like when it's working:
```
PluginA:
- Library plugin that has ACF built in
- acf-pluginb.properties is inside the resources

PluginB:
- Depends on PluginA
- acf-pluginb.properties is NOT in the resources
- MessageKeys are being picked up properly
```

This is an issue for me, as I don't want to pack ACF into every plugin individually as I want to keep a controlled CommandManager that all my plugins use that has some of its own context related stuff.

**Comment by aikar** [comment] 2018-02-04 17:04
You need to re-approach this. Providing ACF in a core util library should be fine, but you should however not register all commands into the same manager, as the manager is bound to the plugin and the plugins life cycle events.

What I suggest is to move all of your shared context, completions and conditions into a separate class file, and then in each implementer, do something like new CoreACFFeatures(this.manager); and the Core ACF Features class will register all the shared code to the provided manager.

then every plugin still creates its own manager, but you can still have a shared code lib for all of the common things.

I actually have plans to implement this exact type of system officially in ACF where you can load "Feature Packs" that will provide context, completions, conditions, annotation aliases, and more as time goes on.

Stuff like Command Cooldowns is what I had in mind.

Then youd be shipping your shared code as a feature pack.

But this doesn't hold you up, you can implement the same logic ahead of time, ACF's feature will just be more "Standardized" way of doing it.

Closing issue since this is a project setup issue / support request and not a bug.

Feel free to jump on IRC/Discord for more assistance.

**Closed by aikar** 2018-02-04 17:04 UTC

**Comment by TehNeon** [comment] 2018-02-04 19:25
I guess I forgot to mention details. I have a CommandManager class that I create an instance for inside each plugin that is relying on the library plugin. Therefore all my plugins are still creating their own manager, I wasn't being really clear with a lot of the details of this issue.
