### ISSUE TITLE
[Request] Show subcommands instead of /help

### ISSUE THREAD

**Issue by TryHardDood** [aikar/commands#21] opened 2017-04-30 12:35 UTC
When I type an invalid subcommand it says: `Unknown Command, please type /help`
Why doesn't is shows the available subcommands with the syntax instead of that message.

Edit: Wouldn't it be better When a player types the basecommand it would show the available subcommands with the syntax instead of nothing?

**Comment by aikar** [comment] 2017-04-30 14:17
This is duplicate of #3 - this is what 3 will resolve.

**Comment by aikar** [comment] 2017-07-18 14:24
Going to reopen this as I think we can resolve some of this independently of the help system, at least until help system is in place.

And if a basecommand does not provide a @Default, we can show list of subcommands.

**Comment by aikar** [comment] 2017-11-14 06:08
@TryHardDood please see https://github.com/aikar/commands/wiki/Unstable-API
and enable help

Then you may add:
```javascript

    @HelpCommand
    public void doHelp(CommandSender sender, CommandHelp help) {
        sendMsg(sender, heading("Anti Grief Help"));
        help.showHelp();
    }
```

This is short for `@UnknownHandler` and `@Default` (if not set) and `@Subcommand("help")` if not set.

And will print help information (and searchable, /cmd help foo will search all metadata for foo and rank results)

This API is nearing release, and im needing feedback from others before I release it.

This will take over the default help message and satisfy your request.

Going to close this, please provide feedback on help system either on #3, or a new issue, or on discord.

**Closed by aikar** 2017-11-14 06:08 UTC
